// app/demos/page.tsx
import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
    title: "Demo Projects",
    description: "Restaurant Website Examples - from simple to complex designs. Created with Next.js, React, and Tailwind CSS.",
};

const DEMOS = [
    {
        href: "/demos/restaurants/gud",
        title: "GUD Restaurant",
        imgUrl: "https://nicojuhari.b-cdn.net/demos/thumbnails/gud-restaurant.webp",
    },
    {
        href: "/demos/restaurants/lusin",
        title: "Lusin Restaurant",
        imgUrl: "https://nicojuhari.b-cdn.net/demos/thumbnails/lusin.jpeg",
    },
    {
        href: "/demos/restaurants/bella-cucina",
        title: "Bella Cucina Restaurant",
        imgUrl: "https://nicojuhari.b-cdn.net/demos/thumbnails/bella-cucina.jpeg",
    },
];

export default function DemosPage() {
    return (
        <main className="min-h-screen bg-gray-100">
            <div className="max-w-5xl mx-auto px-4 py-12">
                <div className="text-center py-10">
                    <h1 className="text-4xl font-bold">Demo Projects</h1>
                    <p className="text-xl text-gray-600 mt-2">Not real websites, but businesses are real.</p>
                </div>
                <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-6 mt-8">
                    {DEMOS.map((demo) => (
                        <Link
                            key={demo.href}
                            href={demo.href}
                            className="bg-white border border-gray-200 rounded-lg overflow-hidden hover:shadow-md transition-shadow"
                        >
                            <img src={demo.imgUrl} alt={demo.title} className="w-full aspect-video object-cover" />
                            <div className="text-lg p-5 font-bold">{demo.title}</div>
                        </Link>
                    ))}
                </div>
                <div className="text-center mt-12">
                    <Link href="/" className="text-sm text-gray-500 hover:text-gray-700 transition-colors">
                        ← Back to nicojuhari.com
                    </Link>
                </div>
            </div>
        </main>
    );
}

// pages/demos/index.vue
<script setup>
definePageMeta({
    layout: 'default'
})

useHead({
    title: `Restaurant Website Examples`,
    bodyAttrs: {
        class: 'bg-gray-100'
    },
    meta: [
        { name: 'keywords', content: 'demo website, restaurant website design, digital food menu' },
        { name: 'description', content: `Restaurant Website Examples - from simple to complex designs. Created with LOVE using Nuxt.js, Vue.js, TailwindCSS and our Free Menu Maker` },
    ],
})

const list = [
    {
        url: 1,
        title: 'Trattoria Bella Italia',
        imgUrl: 'https://nicojuhari.b-cdn.net/demos/thumbnails/trattoria-bella-italia.webp'
    },
    {
        url: 2,
        title: 'GUD Restaurant',
        imgUrl: 'https://nicojuhari.b-cdn.net/demos/thumbnails/gud-restaurant.webp'
    },
    {
        url: 3,
        title: 'La Famiglia Ristorante',
        imgUrl: 'https://nicojuhari.b-cdn.net/demos/thumbnails/la-famiglia-ristorante.webp'
    },
    {
        url: 4,
        title: 'Tony\'s Restaurant',
        imgUrl: 'https://nicojuhari.b-cdn.net/demos/thumbnails/tony-s-restaurant.webp'
    },
    {
        url: 5,
        title: 'Bella Cucina Restaurant',
        imgUrl: 'https://nicojuhari.b-cdn.net/demos/thumbnails/bella-cucina-restaurant.webp'
    },
    {
        url: 6,
        title: 'Mama Mia',
        imgUrl: 'https://nicojuhari.b-cdn.net/demos/thumbnails/mama-mia-restaurant.webp'
    }
]
</script>
<template>
    <section>
        <div class="container">
            <div class="text-center py-9">
                <h1 class="page-title">Restaurant Website Examples</h1>
                <div class="text-xl text-gray-600 mt-2">From simple to complex designs</div>
            </div>
            <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 mt-10 md:mt-16 gap-8">
                <NuxtLink :to="'/demos/restaurant-website-design/'+ item.url" target="_blank"
                    class="bg-white border shadosw border-gray-200 rounded-lg overflow-hidden" v-for="item in list">
                    <div>
                        <img :src="item.imgUrl" class="blosck" :alt="item.title + ' Website Design' " />
                    </div>
                    <div class="text-lg p-6 font-bold">{{ item.title }}</div>
                </NuxtLink>
            </div>
        </div>
    </section>
</template>
