// components/main/home/Hero.vue
<script setup>

</script>
<template>
    <section>
        <div class="container py-10 md:py-20 md:text-xl flex flex-col md:flex-row gap-14 items-center">
            <div class="w-48 h-48 shrink-0">
                <img src="/assets/nick-profile-photo.webp" alt="Nick's profile photo" title="Nick's profile photo"
                    class="rounded-full shadow-md" />
            </div>
            <div class="flex flex-col gap-1">
                <div>Hi, I am Nick</div>
                <h1 class="hero-title mb-4 md:mb-6">Full-Stack Web Developer</h1>
                <h2 class="text-base md:text-xl font-normal">Specializing in pixel-perfect business and restaurant<br>web applications using Nuxt and Appwrite.</h2>
                <div class="flex gap-6 items-center pt-6">
                    <UButton to="/portfolio" class="w-auto flex-grow sm:max-w-28 justify-center" color="brand"
                        title="My Portfolio">Portfolio</UButton>
                    <UButton to="/demos" class="w-auto flex-grow sm:max-w-28 justify-center" variant="outline"
                        color="brand" title="Demo projects">Demos</UButton>
                </div>
            </div>
        </div>
    </section>
</template>

// app/_components/hero.tsx
import Image from "next/image";
import CtaSection from "./cta-section";

export default function Hero() {
    return (
        <section className="section container-sm text-center">
            <div className="flex justify-center mb-6">
                <Image
                    src="/nick-profile-photo.webp"
                    alt="Nick profile photo"
                    width={96}
                    height={96}
                    priority
                    className="rounded-full object-cover border-4 border-white shadow-md"
                />
            </div>
            <p className="text-brand-dusty mb-6 max-md:text-sm">Nick · Software Engineer</p>
            <h1 className="text-[54px] leading-14 sm:text-6xl font-bold mb-8">
                Websites and Web Apps{" "}
                <span className="block text-[45%] sm:text-[55%] font-medium text-muted-foreground">built to grow your business.</span>
            </h1>
            <CtaSection className="py-0! mb-14!" />
        </section>
    );
}
