// app/playground/page.tsx
import type { Metadata } from "next"
import Link from "next/link"

export const metadata: Metadata = {
  title: "Playground",
  description: "A collection of lightweight front-end experiments built with JavaScript, React, and CSS animations.",
}

const PROJECTS = [
  {
    href: "/playground/rain-of-emojis",
    icon: "🎉",
    title: "Rain of Emojis",
    desc: "CSS animations and JavaScript",
  },
  {
    href: "/playground/magic-wand",
    icon: "✨",
    title: "Magic Wand Sparkles",
    desc: "Click to create the magic",
  },
]

export default function PlaygroundPage() {
  return (
    <div className="container-sm py-12">
      <h1 className="text-3xl font-bold text-center mb-2">Playground</h1>
      <p className="text-center text-muted-foreground mb-10">Small experiments, big fun.</p>
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
        {PROJECTS.map((p) => (
          <Link
            key={p.href}
            href={p.href}
            className="flex items-center gap-4 p-5 border rounded-xl bg-white hover:shadow-md hover:-translate-y-0.5 transition-all"
          >
            <span className="text-4xl">{p.icon}</span>
            <div>
              <h3 className="font-bold">{p.title}</h3>
              <p className="text-sm text-muted-foreground">{p.desc}</p>
            </div>
          </Link>
        ))}
      </div>
    </div>
  )
}

// app/pages/playground/index.vue
<script setup>
        useHead({
        title: 'Playground Projects | CSS and JavaScript Experiments',
        meta: [
            { name: 'description', content: 'A collection of lightweight front-end playgrounds of small projects built with Vue, JavaScript, GSAP, and CSS.' },
        ],
})
</script>
<template>
    <div class="container container-sm py-8">
        <h1 class="title text-center my-8">Playground Projects</h1>
        <PlaygroundProjectsList/>
    </div>
</template>
