// app/tools/whitespace-remover/_components/whitespace-remover.tsx
"use client"

import { useState, useMemo } from "react"
import { XIcon, CopyIcon, CheckIcon } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Textarea } from "@/components/ui/textarea"
import { Label } from "@/components/ui/label"
import { Separator } from "@/components/ui/separator"

const REPLACE_OPTIONS = ["dashes", "underscores", "slashes", "keep spaces", "new line", "remove all spaces"] as const
const REPLACE_SYMBOLS: Record<string, string> = {
  dashes: "-", underscores: "_", slashes: "/", "keep spaces": " ", "new line": "\n", "remove all spaces": "",
}
const TRANSFORM_OPTIONS = ["none", "lowercase", "uppercase", "capitalize"] as const

type ReplaceOption = (typeof REPLACE_OPTIONS)[number]
type TransformOption = (typeof TRANSFORM_OPTIONS)[number]

export default function WhitespaceRemover() {
  const [text, setText] = useState("")
  const [replaceWith, setReplaceWith] = useState<ReplaceOption>("dashes")
  const [transform, setTransform] = useState<TransformOption>("none")
  const [keepNewlines, setKeepNewlines] = useState(false)
  const [reverseText, setReverseText] = useState(false)
  const [copied, setCopied] = useState(false)

  const result = useMemo(() => {
    if (!text) return ""
    let out = text.trim()
    const symbol = REPLACE_SYMBOLS[replaceWith]

    if (keepNewlines) {
      out = out.replace(/ +/g, symbol)
    } else {
      out = out.replace(/\s+/g, symbol)
    }

    if (transform === "lowercase") out = out.toLowerCase()
    else if (transform === "uppercase") out = out.toUpperCase()
    else if (transform === "capitalize") {
      out = out.toLowerCase().replace(/\b\w/g, (c) => c.toUpperCase())
    }

    if (reverseText) out = out.split("").reverse().join("")

    if (keepNewlines) {
      out = out.split("\n").map((l) => l.trim().replace(/^[-_/ ]+|[-_/ ]+$/g, "")).join("\n")
    }

    return out
  }, [text, replaceWith, transform, keepNewlines, reverseText])

  const copy = async () => {
    await navigator.clipboard.writeText(result)
    setCopied(true)
    setTimeout(() => setCopied(false), 1500)
  }

  const displayResult = keepNewlines || replaceWith === "new line"
    ? result.split("\n").join("<br>")
    : result

  return (
    <div className="space-y-6">
      <div className="relative">
        <Textarea
          value={text}
          onChange={(e) => setText(e.target.value)}
          placeholder="Add your text here…"
          className="w-full min-h-[160px] resize-none text-sm"
        />
        {text && (
          <Button variant="ghost" size="icon-sm" className="absolute bottom-2 right-2" onClick={() => setText("")}>
            <XIcon className="w-4 h-4" />
          </Button>
        )}
      </div>

      {result && (
        <div>
          <div
            className="border rounded-xl p-3 bg-white text-sm min-h-[60px] max-h-[200px] overflow-y-auto break-all"
            dangerouslySetInnerHTML={{ __html: displayResult }}
          />
          <div className="flex justify-end mt-2">
            <Button variant="outline" size="sm" onClick={copy} className="gap-1.5">
              {copied ? <CheckIcon className="w-3.5 h-3.5" /> : <CopyIcon className="w-3.5 h-3.5" />}
              {copied ? "Copied" : "Copy"}
            </Button>
          </div>
        </div>
      )}

      <div className="border rounded-xl p-4 bg-white grid grid-cols-1 sm:grid-cols-3 gap-6">
        <div>
          <Label className="text-xs uppercase tracking-wide text-muted-foreground mb-3 block">Replace with</Label>
          <div className="space-y-1.5">
            {REPLACE_OPTIONS.map((opt) => (
              <label key={opt} className="flex items-center gap-2 cursor-pointer text-sm">
                <input
                  type="radio"
                  name="replace"
                  value={opt}
                  checked={replaceWith === opt}
                  onChange={() => setReplaceWith(opt)}
                  className="accent-foreground"
                />
                {opt}
              </label>
            ))}
          </div>
        </div>

        <div>
          <Label className="text-xs uppercase tracking-wide text-muted-foreground mb-3 block">Transform</Label>
          <div className="space-y-1.5">
            {TRANSFORM_OPTIONS.map((opt) => (
              <label key={opt} className="flex items-center gap-2 cursor-pointer text-sm">
                <input
                  type="radio"
                  name="transform"
                  value={opt}
                  checked={transform === opt}
                  onChange={() => setTransform(opt)}
                  className="accent-foreground"
                />
                {opt}
              </label>
            ))}
          </div>
        </div>

        <div className="space-y-4">
          <Separator className="sm:hidden" />
          <label className="flex items-center gap-2 cursor-pointer text-sm">
            <input type="checkbox" checked={reverseText} onChange={(e) => setReverseText(e.target.checked)} className="accent-foreground" />
            Reverse the text
          </label>
          <label className="flex items-center gap-2 cursor-pointer text-sm">
            <input type="checkbox" checked={keepNewlines} onChange={(e) => setKeepNewlines(e.target.checked)} className="accent-foreground" />
            Keep new lines
          </label>
        </div>
      </div>
    </div>
  )
}

// app/pages/tools/whitespace-remover.vue
<script setup>
useHead({
    title: 'Whitespace Remover | Replace or Remove the Spaces in Text',
    meta: [
        { name: 'description', content: 'Online Whitespace Remover - quickly replace or remove spaces with hyphens, underscores, slashes, or new lines. Fast, browser-based tool, and FREE' }
    ],
})

const textRaw = ref('')
const loading = ref(false)
const replaceWithSymbol = ref('dashes')
const replaceOptions = ['dashes', 'underscores', 'slashes', 'keep spaces', 'new line', 'remove all spaces']
const replaceOptionsSymbol = {
    dashes: '-',
    underscores: '_',
    slashes: '/',
    'keep spaces': ' ',
    'new line': '\n',
    'remove all spaces': ''
}
const keepNewlines = ref(false)
const transformText = ref('none')
const transformOptions = ['none', 'lowercase', 'uppercase', 'capitalize']

const reverseText = ref(false)

const convertedText = computed(() => {
    let text = '';
    if (!textRaw.value) return text

    //remove around spaces
    let textBefore = textRaw.value.trim()
    
    //replace spaces
    let replaceWith = replaceOptionsSymbol[replaceWithSymbol.value]
    if (keepNewlines.value) {
        text = textBefore.replace(/ +/g, replaceWith)  
    }// Only replace spaces
    else text = textBefore.replace(/\s+/g, replaceWith) // Replace all whitespace (spaces and new lines)

    // transform text
    if (transformText.value === 'lowercase') text = text.toLowerCase()
    if (transformText.value === 'uppercase') text = text.toUpperCase()
    if (transformText.value === 'capitalize') {
        text = text.toLowerCase()
        text = text.replace(/\b\w/g, (char) => char.toUpperCase())
    }

    //reverse text
    if (reverseText.value) text = text.split('').reverse().join('')

    //trim
    if (keepNewlines.value) {
        const lst = text.split('\n').map(line => line.trim().replace(/^[_\-\/\s]+|[_\-\/\s]+$/g, '')); // Remove leading/trailing _,-, or spaces
        // text = lines.join('<br>'); //
        text = lst.join('\n')
    } 
    
    return text
})


//copy to clipboard
const copyToClipboard = () => {
    loading.value = true;
    navigator.clipboard.writeText(convertedText.value);
    setTimeout(() => {
        loading.value = false;
    }, 1000);
}

</script>
<template>
    <div class="container container-sm">
        <h1 class="title mb-2">Whitespace Remover</h1>
        <h2 class="mb-8">Replace text spaces with dashes (hyphens), underscores, slashes or new lines. Simple and fast.</h2>
        <div class="grid grid-cols-1 gap-6">
            <div>
                <div class="relative w-full">
                    <UTextarea v-model="textRaw" class="w-full overflow-auto" :rows="8" :maxrows="12" placeholder="Add your text here ..."></UTextarea>
                    <UButton color="error" variant="subtle" title="Clear the text" class="cursor-pointer absolute right-1.5 bottom-1.5" v-if="textRaw" @click="() => textRaw = ''" icon="i-ph-x-light"></UButton>
                </div>
                <div v-if="convertedText"
                    class="my-6 space-y-4">
                    <div class="p-1.5 py-3 rounded-md bg-white border max-h-[200px] overflow-y-auto">
                        <div v-if="keepNewlines || replaceWithSymbol === 'new line'" v-html="convertedText.split('\n').join('<br>')"></div>
                        <div v-else class="border-0 w-full outline-0 resize-none pl-1 h-full">{{  convertedText }}</div>
                    </div>
                    <div class="flex justify-end">
                        <UButton icon="i-ph-copy-simple-light" label="Copy" variant="subtle"
                            :loading="loading" :disabled="loading" color="success" title="Copy to Clipboard" @click="copyToClipboard" />
        
                    </div>
                </div>
            </div>
            <div class="card grid grid-cols-1 md:grid-cols-3 gap-6">
                <URadioGroup v-model="replaceWithSymbol" legend="Replace with:"
                    :items="replaceOptions" variant="table" size="sm"/>
                <URadioGroup v-model="transformText" legend="Transform:" :items="transformOptions" variant="table" size="sm" />
                <div class="space-y-6 md:mt-6">
                    <USwitch label="Reverse the text?" v-model="reverseText"/>
                    <USwitch label="Keep the new lines?" v-model="keepNewlines" />
                </div>
            </div>
        </div>
        <div class="mt-6 space-y-4">
            <p>Quickly reformat text for filenames(images), URLs, social handles, and any short copy - all in seconds, in your browser.</p>
            <p>Replace or remove spaces with dashes, underscores, slashes, or new lines, and normalize extra whitespace automatically.</p>
            <p>Change case (lower, UPPER, Capitalize), optionally reverse word order, and preserve line breaks when you need them.</p>
            <p>Results update instantly so you can copy clean output straight into CSVs, slugs, or rename files.</p>
            <p>No signup, no uploads - everything runs locally and nothing is stored on our servers.</p>
        </div>
    </div>
</template>
