// app/_components/header.tsx
import Link from "next/link";
import Image from "next/image";
import MobileNav from "./mobile-nav";

const navLinks = [
    { href: "/tools", label: "Tools" },
    { href: "/projects", label: "Projects" },
    { href: "/playground", label: "Playground" },
];

export default function Header() {
    return (
        <header className="sticky top-0 z-50 bg-white/80 backdrop-blur-md border-b">
            <div className="container flex items-center justify-between h-14">
                <Link href="/" title="Nicojuhari" className="shrink-0">
                    <Image src="/nicojuhari-logo.svg" alt="Nicojuhari" width={36} height={36} priority />
                </Link>

                <nav className="hidden md:flex items-center gap-1">
                    {navLinks.map(({ href, label }) => (
                        <Link
                            key={href}
                            href={href}
                            className="px-3 py-2 text-sm font-medium text-muted-foreground hover:text-foreground rounded-md hover:bg-muted transition-colors"
                        >
                            {label}
                        </Link>
                    ))}
                </nav>
                <MobileNav />
            </div>
        </header>
    );
}

// components/menu/Header.vue
<script setup lang="ts">
import { storeToRefs } from 'pinia';
import { useMenuStore } from '~/store/menu'

defineEmits(['open-nav'])
// defineProps(['isOpen'])

const { menu } = storeToRefs(useMenuStore())

</script>
<template>
    <header class="bg-white border-b sticky top-0 z-30 h-14 flex items-center">
        <div class="menu-container flex items-center justify-between gap-6 h-full">
            <div class="flex flex-shrink-0 items-center gap-4">
                <UButton @click="$emit('open-nav')" class="md:hidden" color="gray" variant="soft" icon="i-ph-list" />
                <div class="flex items-center gap-2">
                    <div class="text-lg font-medium w-40 truncate">{{ menu?.configs.title }}</div>
                    <UButton :to="`/tools/free-menu-maker/${$route.params.menu_uid}/settings`" square
                        icon="i-ph-pencil-simple-light" variant="link" color="gray" />
                </div>
            </div>
        </div>
    </header>
</template>
